### PR TITLE
make it compatibile with LVGL 9.1.1

### PR DESCRIPTION
**Pull request by matixan**
I managed to get this working with newer LVGL 9.1 and it works correctly.
However I wasn't able to rotate display using builtin functions inside esp lcd or LVGL
When I tried with manual pixel manipulation results were't good either.
Can someone help me with rotating? My box defines upside down orientation of this 2.8 inch screen.

PS. sorry for broken git

### CODE REVIEW

**Comment by lewisxhe** [comment]
Sorry, I can't merge because the examples are all based on version 8.x. If you update to 9.0, it will cause compilation failure. I will not update it for the time being.

**Comment by LasseKofoed** [comment]
@lewisxhe Please reopen this and make official support for LVGL 9, this product is great but will be doomed if LVGL 9 is not supported.

**Comment by lewisxhe** [comment]
The correct update is to be compatible with the provided examples, rather than having all the examples compile with errors, thus increasing my maintenance costs.

**Comment by matixan** [comment]
> @lewisxhe Please reopen this and make official support for LVGL 9, this product is great but will be doomed if LVGL 9 is not supported.

You can do git diff manually or just directly copy files from my pull request and LVGL 9 will work

**Comment by matixan** [comment]
@LasseKofoed I've removed displays init functions for models which I don't have and implemented software 180 degree rotation

**Pull request closed without merging**
